### PR TITLE
Check Config File Existence

### LINKED ISSUE #3735: CLI does not fail if specified config file specified doesn't exist
I've been surprised by the behaviour so I just wanted to ask if this is by design. Thanks!

Ruby version: 2.5.0
Sidekiq / Pro / Enterprise version(s): Sidekiq 5.0.0

While setting up a sidekiq install, I noticed that if one passes a config file like this:

```
bundle exec sidekiq -C config/foobar.yml -r ./setup/boot.rb
```

with `foobar.yml` an non-existent file, Sidekiq will start anyway & will default to the default configuration.

Note that creating the file then running with `--verbose` I can see the options (e.g. concurrency) taking effect.

### PR DESCRIPTION
**Pull request by Tensho**
Ispired by #4047, Fixes #3735.

Parse `sidekiq.yml[.erb]` only in case:
- `:config_file` is not present as CLI argument
- `:require` is a directory (Rails application)
-  Expanded path to `config/sidekiq.yml[.erb]` against `:require` exists

Example when default config file is considered:
```
$ tree haiku
haiku
└─ config
    └─ sidekiq.yml
$ sidekiq -v -r ./haiku
...
:require => "./haiku"
:config_file => "/Users/tensho/Projects/sidekiq/haiku/config/sidekiq.yml"
...
```

### CODE REVIEW

File: test/test_cli.rb [hunk 1]
```diff
@@ -244,6 +244,18 @@ class TestCLI < Minitest::Test
             assert_equal 3, Sidekiq.options[:queues].count { |q| q == 'seldom' }
           end
         end
+
+        describe 'default config file' do
+          describe 'when required path is a directory' do
+            focus
```
Comment (mperham) [inline test/test_cli.rb]: Forgot to remove this?

Comment (Tensho) [reply test/test_cli.rb]: Yep, sorry, will remove

**Comment by mperham** [comment]
Thanks!

**Comment by navied** [comment]
This is a bit of breaking change, the previous behavior is to check the default config directories on startup now a config flag is required. Might want to make a note of this in the change log. @mperham

**Comment by mperham** [comment]
@navied Could you be more specific?  Sidekiq should always pick up the default config file if none is specified.  If it does not, that's a bug.

**Comment by navied** [comment]
Prior to 5.2.4, in a non-rails sidekiq setup the default config folder of config/sidekiq.yml was picked up. But the default config file is still picked up with a rails w/ sidekiq setup.

**Comment by mperham** [comment]
Thankls, @tensho do you have time to look into this?

File: lib/sidekiq/cli.rb [hunk 2]
```diff
@@ -367,11 +383,8 @@ def parse_options(argv)
         logger.info @parser
         die 1
       end
-      @parser.parse!(argv)
 
-      %w[config/sidekiq.yml config/sidekiq.yml.erb].each do |filename|
```
Comment (navied) [inline lib/sidekiq/cli.rb]: Missing code that is potentially the issue.

**Comment by Tensho** [comment]
I wonder `sidekiq` supports default config file in `config` folder aside of the Rails applications. However, the documentation provides the pretty clear statement, without Rails connotation:
> The Sidekiq configuration file is a YAML file that Sidekiq server uses to configure itself, by default located at config/sidekiq.yml.
Sorry for that oversight 🙇  I'll make an appropriate change.

**Comment by Tensho** [comment]
Adjusted in #4077
