### PR TITLE
Code coverage improvements

### LINKED ISSUE #5363: Code coverage improvements
Sidekiq could use some verification of proper code coverage.

- [x] Verify simplecov runs today with `COVERAGE=1 bundle exec rake`.
- [x] Determine where code coverage is lacking today.
- [x] Improve test suite to increase code coverage where reasonable.
- [ ] Optional: add coverage minimum to CI to fail build if someone adds a bunch of lines but does not provide coverage of those lines

### PR DESCRIPTION
**Pull request by SamArdrey**
Sidekiq could use some verification of proper code coverage.

- [x] Verify simplecov runs today with `COVERAGE=1 bundle exec rake`.
- [x] Determine where code coverage is lacking today.
- [x] Improve test suite to increase code coverage where reasonable - Get coverage up to 90%
- [ ] Optional: add coverage minimum to CI to fail build if someone adds a bunch of lines but does not provide coverage of those lines

closes #5363

### CODE REVIEW

**Comment by SamArdrey** [comment]
Using: https://github.com/marketplace/actions/simplecov-report

File: test/test_web_helpers.rb [hunk 1]
```diff
@@ -125,4 +125,21 @@ def params
     end
     assert_equal "direction=H%3EB&page=B%3CH", obj.qparams("page" => "B<H")
   end
+
+  describe "#format_memory" do
+    it "returnsin KB" do
```
Comment (pusewicz) [inline test/test_web_helpers.rb:130]:
```suggestion
    it "returns in KB" do
```

**Comment by SamArdrey** [comment]
Example of failed coverage: 
```
Fabulous run in 6.720911s, 60.2597 runs/s, 186.2843 assertions/s.
405 runs, 1252 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to /Users/admin/Desktop/sidekiq/coverage. 2061 / 2290 LOC (90.0%) covered.
Line coverage (90.00%) is below the expected minimum coverage (99.00%).
SimpleCov failed with exit 2 due to a coverage related error
rake aborted!
Command failed with status (2)
/Users/admin/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `load'
/Users/admin/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
